"""Schemas for preprocessing plans and executed operations."""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field


class PlanOperation(BaseModel):
    """An individual planned preprocessing step."""
    step_id: int
    operation_name: str
    tool_name: str
    rationale: str
    parameters: Dict[str, Any] = Field(default_factory=dict)
    applied_to: List[str] = Field(default_factory=list)
    fit_on_train_only: bool = True


class PreprocessingPlan(BaseModel):
    """Structured plan generated by agent reasoning."""
    plan_id: str
    target_column: str
    task_type: str
    dataset_summary: str
    operations: List[PlanOperation] = Field(default_factory=list)
    requires_approval: bool = False
    approved: bool = False
    rejection_reason: Optional[str] = None


class TransformationResult(BaseModel):
    """Execution receipt of an applied transformation."""
    step_id: int
    operation_name: str
    tool_name: str
    status: str  # 'success', 'warning', 'failed', 'skipped'
    details: Dict[str, Any] = Field(default_factory=dict)
    columns_before: int
    columns_after: int
    rows_before: int
    rows_after: int
    execution_time_seconds: float = 0.0
